// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function fibonacci(n) {
  const fib = [0, 1];
  let sum = 0;

  for (let i = 2; i <= n + 1; i++) {
    fib[i] = fib[i - 2] + fib[i - 1];
    if (fib[i] % 2 == 0 && fib[i] <= 4000000) {
      sum = sum + fib[i];
    }
  }
  console.log(sum);
}

fibonacci(400);
